### ISSUE TITLE
Fix minutes displayed in alarm list view

### ISSUE THREAD

**Issue by aniketmhatre88** [codepath17/riseandshine#26]
- for single digit number the list view should display minutes with a 0 prepended to it e.g. 08
- Time should be displayed in this format 11:08 am

**Comment by gittify** [comment]
in AlarmCell....
didSet {
            let temp = String(format: "%02d",alarm.time.minute!)
            timeLabel.text = "\(alarm.time.hour!):\(temp) \(alarm.time.meridiem!.rawValue)"
